version: '1.0'

services:
  broker:
    build: broker
    ports:
      - "2550:2550"
    environment:
      - HOSTNAME=broker

  auldfellas:
    build: auldfellas
    depends_on:
      - broker
    environment:
      - HOSTNAME=auldfellas
      - BROKER=broker

  dodgygeezers:
    build: dodgygeezers
    depends_on:
      - broker
    environment:
      - HOSTNAME=dodgygeezers
      - BROKER=broker

  girlsallowed:
    build: girlsallowed
    depends_on:
      - broker
    environment:
      - HOSTNAME=girlsallowed
      - BROKER=broker

  client:
    build: client
    depends_on:
      - broker
      - auldfellas
      - dodgygeezers
      - girlsallowed
    environment:
      - HOSTNAME=client
      - BROKER=broker